/*
 *Original Author:	shko
 */

#include "descriptor.h"

Descriptor::Descriptor(const char* buffer, const int offset, const TableSection* parent)
        : descriptorTag(Utils::getUnsignedByte(buffer[offset])),
          descriptorLength(Utils::getUnsignedByte(buffer[offset + 1])),
          parentTableSection(parent)

{

    privateDataByte.resize(descriptorLength);
    memcpy(&privateDataByte[0], buffer + offset + 2, descriptorLength);
    privateDataByteOffset = offset + 2;

}
Descriptor::~Descriptor(void)
{
    //delete[] privateData;
}


int Descriptor::getDescriptorLength()
{
    return descriptorLength;
}

int Descriptor::getDescriptorTag()
{
    return descriptorTag;
}

const CharVector* Descriptor::getPrivateDataByte()
{
    return &privateDataByte;
}

std::string Descriptor::getDescriptorname()
{
    return getDescriptorname(descriptorTag);
}

#define TAGNAME_MACRO(p) case(p): return #p;
std::string Descriptor::getDescriptorname(const int tag)
{

    switch (tag)
    {
        /** < ISO/IEC 13818-1 */
        TAGNAME_MACRO(TAG_VIDEO_STREAM)
        TAGNAME_MACRO(TAG_AUDIO_STREAM)
        TAGNAME_MACRO(TAG_HIERARCHY)
        TAGNAME_MACRO(TAG_REGISTRATION)
        TAGNAME_MACRO(TAG_DATA_STREAM_ALIGNMENT)
        TAGNAME_MACRO(TAG_TARGET_BACKGROUND_GRID)
        TAGNAME_MACRO(TAG_VIDEO_WINDOW)
        TAGNAME_MACRO(TAG_CONDITIONAL_ACCESS)
        TAGNAME_MACRO(TAG_ISO_639_LANGUAGE)
        TAGNAME_MACRO(TAG_SYSTEM_CLOCK)
        TAGNAME_MACRO(TAG_MULTIPLEX_BUFFER_UTILIZATION)
        TAGNAME_MACRO(TAG_COPYRIGHT)
        TAGNAME_MACRO(TAG_MAXIMUM_BITRATE)
        TAGNAME_MACRO(TAG_PRIVATE_DATA_INDICATOR)
        TAGNAME_MACRO(TAG_SMOOTHING_BUFFER)
        TAGNAME_MACRO(TAG_STD)
        TAGNAME_MACRO(TAG_IBP)
        TAGNAME_MACRO(TAG_CAROUSEL_IDENTIFIER)
        TAGNAME_MACRO(TAG_ASSOCIATION_TAG)
        TAGNAME_MACRO(TAG_DEFERRED_ASSOCIATION_TAG)
        TAGNAME_MACRO(TAG_STREAM_EVENT)
        TAGNAME_MACRO(TAG_AVC_VIDEO)
        TAGNAME_MACRO(TAG_AVC_TIMING_AND_HRD)
        TAGNAME_MACRO(TAG_AAC_MPEG2)
        TAGNAME_MACRO(TAG_JPEG2000VIDEO)

        /** < ETS 300 468 */
        TAGNAME_MACRO(TAG_NETWORK_NAME)
        TAGNAME_MACRO(TAG_SERVICE_LIST)
        TAGNAME_MACRO(TAG_STUFFING)
        TAGNAME_MACRO(TAG_SATELLITE_DELIVERY_SYSTEM)
        TAGNAME_MACRO(TAG_CABLE_DELIVERY_SYSTEM)
        TAGNAME_MACRO(TAG_VBI_DATA)
        TAGNAME_MACRO(TAG_VBI_TELETEXT)
        TAGNAME_MACRO(TAG_BOUQUET_NAME)
        TAGNAME_MACRO(TAG_SERVICE)
        TAGNAME_MACRO(TAG_COUNTRY_AVAILABILITY)
        TAGNAME_MACRO(TAG_LINKAGE)
        TAGNAME_MACRO(TAG_NVOD_REFERENCE)
        TAGNAME_MACRO(TAG_TIME_SHIFTED_SERVICE)
        TAGNAME_MACRO(TAG_SHORT_EVENT)
        TAGNAME_MACRO(TAG_EXTENDED_EVENT)
        TAGNAME_MACRO(TAG_TIME_SHIFTED_EVENT)
        TAGNAME_MACRO(TAG_COMPONENT)
        TAGNAME_MACRO(TAG_MOSAIC)
        TAGNAME_MACRO(TAG_STREAM_IDENTIFIER)
        TAGNAME_MACRO(TAG_CA_IDENTIFIER)
        TAGNAME_MACRO(TAG_CONTENT)
        TAGNAME_MACRO(TAG_PARENTAL_RATING)
        TAGNAME_MACRO(TAG_TELETEXT)
        TAGNAME_MACRO(TAG_TELEPHONE)
        TAGNAME_MACRO(TAG_LOCAL_TIME_OFFSET)
        TAGNAME_MACRO(TAG_SUBTITLING)
        TAGNAME_MACRO(TAG_TERRESTRIAL_DELIVERY_SYSTEM)
        TAGNAME_MACRO(TAG_MULTILINGUAL_NETWORK_NAME)
        TAGNAME_MACRO(TAG_MULTILINGUAL_BOUQUET_NAME)
        TAGNAME_MACRO(TAG_MULTILINGUAL_SERVICE_NAME)
        TAGNAME_MACRO(TAG_MULTILINGUAL_COMPONENT)
        TAGNAME_MACRO(TAG_PRIVATE_DATA_SPECIFIER)
        TAGNAME_MACRO(TAG_SERVICE_MOVE)
        TAGNAME_MACRO(TAG_SHORT_SMOOTHING_BUFFER)
        TAGNAME_MACRO(TAG_FREQUENCY_LIST)
        TAGNAME_MACRO(TAG_PARTIAL_TRANSPORT_STREAM)
        TAGNAME_MACRO(TAG_DATA_BROADCAST)
        TAGNAME_MACRO(TAG_SCRAMBLING)
        TAGNAME_MACRO(TAG_DATA_BROADCAST_ID)
        TAGNAME_MACRO(TAG_TRANSPORT_STREAM)
        TAGNAME_MACRO(TAG_DSNG)
        TAGNAME_MACRO(TAG_PDC)
        TAGNAME_MACRO(TAG_DOLBY_AC3)
        TAGNAME_MACRO(TAG_ANCILLARY_DATA)
        TAGNAME_MACRO(TAG_CELL_LIST)
        TAGNAME_MACRO(TAG_CELL_FREQ_LIST)
        TAGNAME_MACRO(TAG_ANNOUNCEMENT_SUPPORT)
        TAGNAME_MACRO(TAG_APPLICATION_SIGNALLING)
        TAGNAME_MACRO(TAG_ADAPTATION_FIELD_DATA)
        TAGNAME_MACRO(TAG_SVC_IDENTIFIER)
        TAGNAME_MACRO(TAG_SVC_AVAILABILITY)
        TAGNAME_MACRO(TAG_DEFAULT_AUTHORITY)
        TAGNAME_MACRO(TAG_RELATED_CONTENT)
        TAGNAME_MACRO(TAG_TVA_ID)
        TAGNAME_MACRO(TAG_CONTENT_IDENTIFIER)
        TAGNAME_MACRO(TAG_TIME_SLICE_FEC_IDENTIFIER)
        TAGNAME_MACRO(TAG_ECM_REPETITION_RATE)
        TAGNAME_MACRO(TAG_S2_SATELLITE_DELIVERY_SYSTEM)
        TAGNAME_MACRO(TAG_ENHANCED_AC3)
        TAGNAME_MACRO(TAG_DTS)
        TAGNAME_MACRO(TAG_AAC)
        TAGNAME_MACRO(TAG_XAIT_LOCATION)
        TAGNAME_MACRO(TAG_FTA_CONTENT_MANAGEMENT)
        TAGNAME_MACRO(TAG_EXTENSION)



        default:
            return "not implemented yet...";

    }
}


